### PR TITLE
action.go, menu.go, declarative/action.go, examples/actions: fix radio button menu items

### LINKED ISSUE #65: Walk does not work correctly with radiobutton menu items
- Clicking on a checked exclusive menu item incorrectly unsets `walk.Action.checked` for that item;
- Walk doesn't unset `walk.Action.checked` for other items in a group when it marks a menu item as checked.

As a result, the boolean `checked` flag becomes out-of-sync with the displayed item state.
Which in turn may result in weird issues like this, where more than one item appears to be checked:
image
Similar, but with _Mullvad VPN_ menu item being unchecked:
image

### PR DESCRIPTION
**Pull request by nickkhyl**
This prevents radio button menu items from being unchecked when a user selects an already checked item. It also updates other item states in an exclusivity group when a radio button menu item is checked programmatically or by a user.

Finally, it allows to create radio button menu items using the declarative syntax and updates examples/actions to demonstrate the new behavior.

Fixes #65

### CODE REVIEW

File: actionlist.go [hunk 1]
```diff
@@ -147,6 +149,41 @@ func (l *ActionList) positionsForExclusiveCheck(action *Action) (first, last, in
...
+				continue
+			}
+		}
+		if i < first {
+			continue
+		}
+		if i > last {
+			break
+		}
+		if err := a.SetChecked(false); err != nil {
```
Comment (dblohm7) [inline actionlist.go:179]: This will end up triggering `(*Menu).onActionChanged` on the previously checked `Action` and trigger a redundant `SetMenuItemInfo` call.

I suppose for one item that isn't too important; I'm thinking that the additional complexity around suppressing that extra call isn't worth the effort. I'm mainly noting this for reference purposes.

**Review by dblohm7 — APPROVED** [review]

**Comment by dblohm7** [comment]
(Also, thanks for adding declarative support!)

File: actionlist.go (hunk 1 above)
Comment (nickkhyl) [reply actionlist.go:179]: I agree.

I didn't want to suppress all `Action.changedHandlers`, as other handlers (e.g. `ownerDrawnMenuItemInfo`) might need to receive a change notification when an action gets unchecked. We could keep track of changes made since the last `SetMenuItemInfo` call and conditionally suppress it, but I too don't think it's worth the effort. Also, calling `SetMenuItemInfo` for an exclusive Action being checked is probably redundant as well since we also call `CheckMenuRadioItem` for it.
